"""全局常量"""

APP_NAME: str = "sop-poka-yoke"
APP_VERSION: str = "1.0.0"

CONFIDENCE_OK_THRESHOLD: float = 0.85
CONFIDENCE_WARN_THRESHOLD: float = 0.60

DEFAULT_STEP_TIMEOUT_SECONDS: float = 60.0
DEFAULT_DEBOUNCE_SECONDS: float = 0.5

VIDEO_FPS: int = 25
VIDEO_BUFFER_SECONDS: int = 10
SNAPSHOT_QUALITY: int = 85
