"""全局常量"""

APP_NAME = "sop-poka-yoke"
APP_VERSION = "1.0.0"

CONFIDENCE_OK_THRESHOLD = 0.85
CONFIDENCE_WARN_THRESHOLD = 0.60

DEFAULT_STEP_TIMEOUT_SECONDS = 60.0
DEFAULT_DEBOUNCE_SECONDS = 0.5

VIDEO_FPS = 25
VIDEO_BUFFER_SECONDS = 10
SNAPSHOT_QUALITY = 85
